weatherscrapper:
  version: 0.0.1
  log:
    requests:
      enabled: true
spring:
  profiles:
    active: "dev"
  servlet:
    multipart:
      max-file-size: -1
      enabled: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    check-template-location: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
  data:
    rest:
      base-path: /repo
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  servlet:
    context-path:
  port: 8080